import type { Plot } from "../types/plot";

export const plotsSectionCopy = {
  eyebrow: "Prieinami sklypai",
  title: "Raskite tinkamą vietą savo investicijai.",
  intro:
    "VCIIP TECH teritorijoje formuojami skirtingo dydžio sklypai, pritaikyti pažangiai gamybai, technologijų ir laboratorijų veiklai. Žemiau galite matyti šiuo metu prieinamus sklypus ir jų statusą.",
  disclaimer: "* Dalis infrastruktūros vystoma etapais iki 2027–2028 m.",
  bottomTitle: "Neradote tinkamo sklypo?",
  bottomText:
    "Jeigu ieškote kitokio dydžio ar paskirties sklypo, susisiekite su mūsų komanda – padėsime įvertinti galimybes.",
  bottomCta: "Susisiekti dėl sklypo",
  bottomCtaHref: "/kontaktai?interest=tech",
  primaryCta: "Domina šis sklypas",
  secondaryCta: "Atsisiųsti teritorijos planą",
};

export const fallbackPlots: Plot[] = [
  {
    id: "plot-a",
    letter: "A",
    name: "Sklypas A",
    area: "0,82 ha",
    purpose: ["Technologijos", "Pažangi gamyba"],
    status: "available",
    infrastructure: {
      electric: true,
      water: true,
      gas: true,
      communications: true,
    },
    mapPosition: { left: "20%", top: "36%" },
    ctaHref: "/kontaktai?interest=tech",
    planDownloadUrl: null,
  },
  {
    id: "plot-b",
    letter: "B",
    name: "Sklypas B",
    area: "1,25 ha",
    purpose: ["Gamyba"],
    status: "reserved",
    infrastructure: {
      electric: true,
      water: true,
      gas: true,
      communications: true,
    },
    mapPosition: { left: "34%", top: "54%" },
    ctaHref: "/kontaktai?interest=tech",
    planDownloadUrl: null,
  },
  {
    id: "plot-c",
    letter: "C",
    name: "Sklypas C",
    area: "2,40 ha",
    purpose: ["Laboratorijos", "Technologijos"],
    status: "available",
    infrastructure: {
      electric: true,
      water: true,
      gas: false,
      communications: true,
    },
    mapPosition: { left: "48%", top: "32%" },
    ctaHref: "/kontaktai?interest=tech",
    planDownloadUrl: null,
  },
  {
    id: "plot-d",
    letter: "D",
    name: "Sklypas D",
    area: "1,60 ha",
    purpose: ["Pažangi gamyba"],
    status: "planned",
    infrastructure: {
      electric: true,
      water: true,
      gas: true,
      communications: false,
    },
    mapPosition: { left: "62%", top: "50%" },
    ctaHref: "/kontaktai?interest=tech",
    planDownloadUrl: null,
  },
  {
    id: "plot-e",
    letter: "E",
    name: "Sklypas E",
    area: "3,10 ha",
    purpose: ["Technologijos", "Gamyba"],
    status: "available",
    infrastructure: {
      electric: true,
      water: true,
      gas: true,
      communications: true,
    },
    mapPosition: { left: "76%", top: "38%" },
    ctaHref: "/kontaktai?interest=tech",
    planDownloadUrl: null,
  },
];
